"""Author the shadcn-maps `map-data` file for the bidding zones (Phase 3 coarse layer).

Regions = the model's zones (entsoe-py polygons; Bornholm from GISCO NUTS3 DK014), drawn in the
frontend's flow-pixel coordinate system (the same Web-Mercator fitBounds as
frontend/src/lib/projection.ts) so the choropleth can sit inside React Flow's viewport and align
exactly with the node positions.
Output: frontend/src/components/shadcnmaps/map-data/northern-europe.ts

    python -m emap_topology.mapdata
"""

from __future__ import annotations

import json
import math

from shapely.geometry import MultiPolygon, Polygon, shape
from shapely.geometry.base import BaseGeometry
from shapely.ops import unary_union

from .config import DATA, ROOT, ZONES
from .io import read_zone_polygons

# Must equal frontend/src/lib/topology.ts (WORLD, padding) and NORTHERN_EUROPE_BOUNDS.
WORLD = 36000.0
PADDING = 600.0
BOUNDS = {"west": 3.0, "south": 49.0, "east": 31.0, "north": 71.0}
SIMPLIFY_DEG = 0.012  # ~1 km: keeps the file small, invisible at any coarse zoom
OUT = (
    ROOT.parent
    / "frontend"
    / "src"
    / "components"
    / "shadcnmaps"
    / "map-data"
    / "northern-europe.ts"
)


def mercator_unit(lon: float, lat: float) -> tuple[float, float]:
    phi = math.radians(max(-85.05112878, min(85.05112878, lat)))
    return (lon + 180.0) / 360.0, (
        1.0 - math.log(math.tan(phi) + 1.0 / math.cos(phi)) / math.pi
    ) / 2.0


def fit_bounds() -> tuple[float, tuple[float, float]]:
    """(scale, translate) exactly as projection.ts fitBounds(bounds, {WORLD, WORLD}, PADDING)."""
    inner = WORLD - 2 * PADDING
    nwx, nwy = mercator_unit(BOUNDS["west"], BOUNDS["north"])
    sex, sey = mercator_unit(BOUNDS["east"], BOUNDS["south"])
    uw, uh = sex - nwx, sey - nwy
    scale = min(inner / uw, inner / uh)
    tx = PADDING + (inner - uw * scale) / 2 - nwx * scale
    ty = PADDING + (inner - uh * scale) / 2 - nwy * scale
    return scale, (tx, ty)


def project(lon: float, lat: float, scale: float, tr: tuple[float, float]) -> tuple[float, float]:
    ux, uy = mercator_unit(lon, lat)
    return ux * scale + tr[0], uy * scale + tr[1]


def _ring_path(coords, scale, tr) -> str:
    pts = [project(x, y, scale, tr) for x, y in coords]
    return "M" + "L".join(f"{x:.1f} {y:.1f}" for x, y in pts) + "Z"


def geometry_path(geom: BaseGeometry, scale: float, tr) -> str:
    polys = list(geom.geoms) if isinstance(geom, MultiPolygon) else [geom]
    parts = []
    for p in polys:
        if not isinstance(p, Polygon) or p.is_empty:
            continue
        parts.append(_ring_path(p.exterior.coords, scale, tr))
        for hole in p.interiors:
            parts.append(_ring_path(hole.coords, scale, tr))
    return "".join(parts)


def build() -> str:
    polys = read_zone_polygons()
    nuts = json.loads((DATA / "nuts3_dk.geojson").read_text(encoding="utf-8"))
    bornholm = next(
        shape(f["geometry"]) for f in nuts["features"] if f["properties"]["id"] == "DK014"
    )
    polys["DK2"] = unary_union([polys["DK2"], bornholm])
    scale, tr = fit_bounds()
    regions = []
    for z in ZONES.values():
        if z.id not in polys:
            continue  # GB: no polygon shipped (hub node only)
        g = polys[z.id].simplify(SIMPLIFY_DEG, preserve_topology=True)
        c = g.representative_point()
        lx, ly = project(c.x, c.y, scale, tr)
        regions.append(
            {"id": z.id, "name": z.name, "abbreviation": z.id, "labelX": round(lx, 1),
             "labelY": round(ly, 1), "metadata": {"country": z.country, "detail": z.detail},
             "path": geometry_path(g, scale, tr)}
        )  # fmt: skip
    meta = {
        "world": WORLD,
        "padding": PADDING,
        "bounds": BOUNDS,
        "scale": scale,
        "translate": list(tr),
    }
    lines = [
        "// GENERATED by topology/emap_topology/mapdata.py from the entsoe-py bidding-zone",
        "// polygons (+ GISCO NUTS3 DK014 for Bornholm). Coordinates: React Flow world pixels",
        "// (the Web-Mercator fitBounds of src/lib/projection.ts), aligned with the nodes.",
        "import type { MapData } from '@/components/shadcnmaps/types'",
        "",
        f"export const northernEuropeProjection = {json.dumps(meta)} as const",
        "",
        "export const northernEuropeMapData = {",
        "  id: 'northern-europe',",
        "  name: 'Northern Europe bidding zones',",
        f"  viewBox: '0 0 {WORLD:.0f} {WORLD:.0f}',",
        "  regions: [",
    ]
    for r in regions:
        lines.append(f"    {json.dumps(r)},")
    lines += ["  ],", "} as const satisfies MapData", ""]
    return "\n".join(lines)


def main() -> None:
    text = build()
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(text, encoding="utf-8")
    print(f"wrote {OUT} ({len(text) / 1024:.0f} kB)")


if __name__ == "__main__":
    main()
