// Generate `src/lib/api-types.d.ts` from the backend's OpenAPI document.
// The backend (pydantic models) is the single source of truth; this file keeps
// the frontend from drifting. Run `npm run gen:api` after changing the API;
// `npm run gen:api -- --check` fails if the committed types are stale (CI).
import { execFileSync } from 'node:child_process'
import { existsSync, readFileSync, writeFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import path from 'node:path'
import openapiTS, { astToString } from 'openapi-typescript'

const here = path.dirname(fileURLToPath(import.meta.url))
const backend = path.resolve(here, '../../backend')
const out = path.resolve(here, '../src/lib/api-types.d.ts')
const check = process.argv.includes('--check')

const candidates = [
  path.join(backend, '.venv', 'Scripts', 'python.exe'),
  path.join(backend, '.venv', 'bin', 'python'),
]
const python = process.env.EMAP_PYTHON ?? candidates.find((p) => existsSync(p))
if (!python) {
  console.error('backend venv not found; create it first (see README) or set EMAP_PYTHON')
  process.exit(2)
}

const spec = execFileSync(python, ['scripts/export_openapi.py'], { cwd: backend, encoding: 'utf8' })
const ast = await openapiTS(JSON.parse(spec), { exportType: true })
const header =
  '// GENERATED by scripts/gen-api.mjs from the backend OpenAPI document. DO NOT EDIT.\n' +
  '// Regenerate with `npm run gen:api` (frontend/).\n\n'
const text = header + astToString(ast)

if (check) {
  const current = existsSync(out) ? readFileSync(out, 'utf8') : ''
  if (current !== text) {
    console.error(`api-types.d.ts is stale — run: npm run gen:api`)
    process.exit(1)
  }
  console.log('api-types.d.ts is up to date')
} else {
  writeFileSync(out, text)
  console.log(`wrote ${path.relative(process.cwd(), out)}`)
}
