// GENERATED by scripts/gen-api.mjs from the backend OpenAPI document. DO NOT EDIT.
// Regenerate with `npm run gen:api` (frontend/).

export type paths = {
    "/api/ingest/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Ingest Status
         * @description Last run / rows / error per scheduled ingestion job.
         */
        get: operations["ingest_status_api_ingest_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/samples": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Samples
         * @description Canonical `Sample` rows for one (entity, quantity) in [start, end). Default: last 24h.
         */
        get: operations["samples_api_samples_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/series": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Series
         * @description Time series for any entity: stored rows for zones / classes / corridors, derived
         *     (distribution rule) for DK plant, dg and load nodes. Default window: last 31 days.
         */
        get: operations["get_series_api_series_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/state": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get State
         * @description Per-node state vectors (MVP.md §3.2), corridor flows, zone totals + raw residual and
         *     cluster aggregates at instant t (default: now, floored to the 5-min grid).
         */
        get: operations["get_state_api_state_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/topology": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Topology
         * @description The static network: canonical nodes/edges at the finest level plus the precomputed
         *     cluster views for coarser levels (service A artifact, validated at startup).
         */
        get: operations["get_topology_api_topology_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
};
export type webhooks = Record<string, never>;
export type components = {
    schemas: {
        /** BundledEdge */
        BundledEdge: {
            /** From */
            from: string;
            /** Id */
            id: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "ac_line" | "hvdc_link" | "interconnector";
            /** Length Km */
            length_km: number | null;
            /** Members */
            members: string[];
            /** Rating Mw */
            rating_mw: number | null;
            /** To */
            to: string;
        };
        /** ClusterNode */
        ClusterNode: {
            /** Capacity Mw */
            capacity_mw: {
                [key: string]: number;
            };
            /** Counts */
            counts: {
                [key: string]: number;
            };
            /** Id */
            id: string;
            /** Lat */
            lat: number;
            /** Level */
            level: number;
            /** Lon */
            lon: number;
            /** Members */
            members: string[];
            /** Name */
            name: string;
            /** Zone */
            zone: string;
        };
        /** ClusterState */
        ClusterState: {
            /** Demand */
            demand?: number | null;
            /** Id */
            id: string;
            /** Level */
            level: number;
            /** Net Injection */
            net_injection?: number | null;
            /** P Gen */
            p_gen?: number | null;
            /**
             * Quality
             * @enum {string}
             */
            quality: "measured" | "interpolated" | "estimated" | "missing";
        };
        /** DbHealth */
        DbHealth: {
            /** Migrations */
            migrations: components["schemas"]["MigrationInfo"][];
            /** Path */
            path: string;
        };
        /** Edge */
        Edge: {
            /** From */
            from: string;
            /** Id */
            id: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "ac_line" | "hvdc_link" | "interconnector";
            /** Length Km */
            length_km?: number | null;
            /**
             * Rating Mw
             * @description thermal limit / NTC; null = unrated virtual connection (bus->load)
             */
            rating_mw: number | null;
            /** To */
            to: string;
        };
        /** EdgeState */
        EdgeState: {
            /** Flow */
            flow?: number | null;
            /** Flow Raw */
            flow_raw?: number | null;
            /** Id */
            id: string;
            /** Loading */
            loading?: number | null;
            /**
             * Quality
             * @enum {string}
             */
            quality: "measured" | "interpolated" | "estimated" | "missing";
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** Health */
        Health: {
            db: components["schemas"]["DbHealth"];
            /** Status */
            status: string;
            /**
             * Time Utc
             * Format: date-time
             */
            time_utc: string;
            /** Version */
            version: string;
        };
        /** JobStatus */
        JobStatus: {
            /** Dataset */
            dataset: string;
            /**
             * Failures
             * @default 0
             */
            failures: number;
            /** Interval S */
            interval_s: number;
            /** Last Error */
            last_error?: string | null;
            /** Last Ok Utc */
            last_ok_utc?: string | null;
            /**
             * Last Rows
             * @default 0
             */
            last_rows: number;
            /** Last Started Utc */
            last_started_utc?: string | null;
            /** Name */
            name: string;
            /**
             * Runs
             * @default 0
             */
            runs: number;
        };
        /** LevelInfo */
        LevelInfo: {
            /** Description */
            description: string;
            /** Level */
            level: number;
            /** Name */
            name: string;
        };
        /** LevelView */
        LevelView: {
            /** Edges */
            edges: components["schemas"]["BundledEdge"][];
            /** Nodes */
            nodes: components["schemas"]["ClusterNode"][];
        };
        /** MigrationInfo */
        MigrationInfo: {
            /**
             * Applied At
             * Format: date-time
             */
            applied_at: string;
            /** Name */
            name: string;
            /** Version */
            version: number;
        };
        /** Node */
        Node: {
            /**
             * Capacity Mw
             * @description nameplate power rating (MW); storage: P_max
             */
            capacity_mw?: number | null;
            /**
             * Cluster
             * @description level -> cluster_id; membership in Π_0..Π_L
             */
            cluster?: {
                [key: string]: string;
            };
            /**
             * Co2 Intensity
             * @description tCO2/MWh
             */
            co2_intensity?: number | null;
            /**
             * Dist Key
             * @description share of the zone aggregate this node receives (bus->zone rule, Phase 2)
             */
            dist_key?: number | null;
            /**
             * Energy Mwh
             * @description storage E_max (MWh)
             */
            energy_mwh?: number | null;
            /** Fuel */
            fuel?: string | null;
            /**
             * Id
             * @description stable canonical id
             */
            id: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "source" | "grid" | "consumption" | "storage";
            /** Lat */
            lat: number;
            /** Lon */
            lon: number;
            /** Name */
            name: string;
            /**
             * Voltage Kv
             * @description grid bus nominal voltage
             */
            voltage_kv?: number | null;
            /**
             * Zone
             * @description bidding zone, e.g. 'DK1'
             */
            zone: string;
        };
        /** NodeState */
        NodeState: {
            /** Delta 1H */
            delta_1h?: number | null;
            /** Demand */
            demand?: number | null;
            /** Duration H */
            duration_h?: number | null;
            /** Id */
            id: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "source" | "grid" | "consumption" | "storage";
            /** Loading */
            loading?: number | null;
            /** Net Injection */
            net_injection?: number | null;
            /** Net Sign */
            net_sign?: number | null;
            /** P Gen */
            p_gen?: number | null;
            /** P Store */
            p_store?: number | null;
            /**
             * Quality
             * @enum {string}
             */
            quality: "measured" | "interpolated" | "estimated" | "missing";
            /** Rho */
            rho?: number | null;
            /** Soc */
            soc?: number | null;
            /** T Flow */
            t_flow?: number | null;
            /** U */
            u?: number | null;
        };
        /**
         * ReconciledZone
         * @description n* = argmin ‖W^{1/2}(n − ñ)‖² s.t. the zone identity closes (MVP.md §3.4).
         */
        ReconciledZone: {
            /** Adjustments */
            adjustments: {
                [key: string]: number;
            };
            /** By Class */
            by_class: {
                [key: string]: number;
            };
            /** Demand */
            demand: number;
            /** Exchange */
            exchange: number;
            /** Flows */
            flows: {
                [key: string]: number;
            };
            /** P Gen */
            p_gen: number;
            /** Weights */
            weights: {
                [key: string]: number;
            };
        };
        /**
         * Sample
         * @description One observation on the canonical time grid.
         *
         *     Join key is (entity_id, quantity, t_utc); `source` is kept in the store's
         *     uniqueness key so two providers may report the same quantity side by side.
         *     A `quality == 'missing'` row carries `value=None` (a dense grid may need an
         *     explicit gap); every other quality requires a finite value.
         */
        Sample: {
            /** Entity Id */
            entity_id: string;
            /**
             * Entity Kind
             * @enum {string}
             */
            entity_kind: "node" | "edge";
            /**
             * Quality
             * @enum {string}
             */
            quality: "measured" | "interpolated" | "estimated" | "missing";
            /**
             * Quantity
             * @enum {string}
             */
            quantity: "p_gen" | "demand" | "flow" | "soc" | "price" | "strain" | "residual" | "residual_hat" | "co2_intensity";
            /**
             * Resolution
             * @enum {string}
             */
            resolution: "PT5M" | "PT15M" | "PT60M";
            /**
             * Source
             * @enum {string}
             */
            source: "energinet" | "entsoe" | "pypsa" | "derived";
            /**
             * T Utc
             * Format: date-time
             */
            t_utc: string;
            /**
             * Unit
             * @enum {string}
             */
            unit: "MW" | "MWh" | "EUR/MWh" | "ratio" | "tCO2/MWh";
            /** Value */
            value: number | null;
        };
        /** SeriesPoint */
        SeriesPoint: {
            /**
             * Q
             * @enum {string}
             */
            q: "measured" | "interpolated" | "estimated" | "missing";
            /**
             * T
             * Format: date-time
             */
            t: string;
            /** V */
            v: number;
        };
        /** SeriesResponse */
        SeriesResponse: {
            /** Derived From */
            derived_from?: string | null;
            /** Entity Id */
            entity_id: string;
            /** Points */
            points: components["schemas"]["SeriesPoint"][];
            /**
             * Quantity
             * @enum {string}
             */
            quantity: "p_gen" | "demand" | "flow" | "soc" | "price" | "strain" | "residual" | "residual_hat" | "co2_intensity";
            /**
             * Unit
             * @enum {string}
             */
            unit: "MW" | "MWh" | "EUR/MWh" | "ratio" | "tCO2/MWh";
        };
        /** State */
        State: {
            /** Clusters */
            clusters: {
                [key: string]: {
                    [key: string]: components["schemas"]["ClusterState"];
                };
            };
            /**
             * Computed At Utc
             * Format: date-time
             */
            computed_at_utc: string;
            /** Edges */
            edges: {
                [key: string]: components["schemas"]["EdgeState"];
            };
            /** Nodes */
            nodes: {
                [key: string]: components["schemas"]["NodeState"];
            };
            /**
             * Step
             * @default PT5M
             * @constant
             */
            step: "PT5M";
            /**
             * T Utc
             * Format: date-time
             */
            t_utc: string;
            /** Zones */
            zones: {
                [key: string]: components["schemas"]["ZoneState"];
            };
        };
        /** Topology */
        Topology: {
            /** Edge Members */
            edge_members: {
                [key: string]: string[];
            };
            /** Edges */
            edges: components["schemas"]["Edge"][];
            /** Load Key Detail */
            load_key_detail?: {
                [key: string]: {
                    [key: string]: number;
                };
            };
            meta: components["schemas"]["TopologyMeta"];
            /** Nodes */
            nodes: components["schemas"]["Node"][];
            /** Views */
            views: {
                [key: string]: components["schemas"]["LevelView"];
            };
            /** Zones */
            zones: components["schemas"]["ZoneInfo"][];
        };
        /** TopologyMeta */
        TopologyMeta: {
            /** Builder */
            builder: string;
            /** Built At Utc */
            built_at_utc: string;
            /** Distribution Rule */
            distribution_rule?: {
                [key: string]: string;
            };
            /** Finest Level */
            finest_level: number;
            /** Levels */
            levels: components["schemas"]["LevelInfo"][];
            /** Params */
            params: {
                [key: string]: unknown;
            };
            /** Sources */
            sources: {
                [key: string]: string;
            }[];
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** ZoneInfo */
        ZoneInfo: {
            /** Country */
            country: string;
            /** Detail */
            detail: boolean;
            /** Id */
            id: string;
            /** Lat */
            lat: number;
            /** Lon */
            lon: number;
            /** Name */
            name: string;
        };
        /** ZoneState */
        ZoneState: {
            /**
             * By Class
             * @default {}
             */
            by_class: {
                [key: string]: number;
            };
            /** Co2 Intensity */
            co2_intensity?: number | null;
            /** Demand */
            demand?: number | null;
            /** Demand Age Min */
            demand_age_min?: number | null;
            /**
             * Demand Quality
             * @default missing
             * @enum {string}
             */
            demand_quality: "measured" | "interpolated" | "estimated" | "missing";
            /** Exchange */
            exchange?: number | null;
            /** Id */
            id: string;
            /** Live */
            live: boolean;
            /** P Gen */
            p_gen?: number | null;
            /** Price */
            price?: number | null;
            reconciled?: components["schemas"]["ReconciledZone"] | null;
            /** Residual */
            residual?: number | null;
            /** Residual Hat */
            residual_hat?: number | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
};
export type $defs = Record<string, never>;
export interface operations {
    ingest_status_api_ingest_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobStatus"][];
                };
            };
        };
    };
    samples_api_samples_get: {
        parameters: {
            query: {
                entity_id: string;
                quantity: "p_gen" | "demand" | "flow" | "soc" | "price" | "strain" | "residual" | "residual_hat" | "co2_intensity";
                start?: string | null;
                end?: string | null;
                source?: ("energinet" | "entsoe" | "pypsa" | "derived") | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Sample"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_series_api_series_get: {
        parameters: {
            query: {
                entity_id: string;
                quantity: "p_gen" | "demand" | "flow" | "soc" | "price" | "strain" | "residual" | "residual_hat" | "co2_intensity";
                start?: string | null;
                end?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SeriesResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_state_api_state_get: {
        parameters: {
            query?: {
                t?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["State"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_topology_api_topology_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Topology"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
}
