// GENERATED by scripts/gen-api.mjs from the backend OpenAPI document. DO NOT EDIT.
// Regenerate with `npm run gen:api` (frontend/).

export type paths = {
    "/api/samples": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Samples
         * @description Canonical `Sample` rows for one (entity, quantity) in [start, end). Default: last 24h.
         */
        get: operations["samples_api_samples_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
};
export type webhooks = Record<string, never>;
export type components = {
    schemas: {
        /** DbHealth */
        DbHealth: {
            /** Migrations */
            migrations: components["schemas"]["MigrationInfo"][];
            /** Path */
            path: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** Health */
        Health: {
            db: components["schemas"]["DbHealth"];
            /** Status */
            status: string;
            /**
             * Time Utc
             * Format: date-time
             */
            time_utc: string;
            /** Version */
            version: string;
        };
        /** MigrationInfo */
        MigrationInfo: {
            /**
             * Applied At
             * Format: date-time
             */
            applied_at: string;
            /** Name */
            name: string;
            /** Version */
            version: number;
        };
        /**
         * Sample
         * @description One observation on the canonical time grid.
         *
         *     Join key is (entity_id, quantity, t_utc); `source` is kept in the store's
         *     uniqueness key so two providers may report the same quantity side by side.
         *     A `quality == 'missing'` row carries `value=None` (a dense grid may need an
         *     explicit gap); every other quality requires a finite value.
         */
        Sample: {
            /** Entity Id */
            entity_id: string;
            /**
             * Entity Kind
             * @enum {string}
             */
            entity_kind: "node" | "edge";
            /**
             * Quality
             * @enum {string}
             */
            quality: "measured" | "interpolated" | "estimated" | "missing";
            /**
             * Quantity
             * @enum {string}
             */
            quantity: "p_gen" | "demand" | "flow" | "soc" | "price" | "strain" | "residual";
            /**
             * Resolution
             * @enum {string}
             */
            resolution: "PT5M" | "PT15M" | "PT60M";
            /**
             * Source
             * @enum {string}
             */
            source: "energinet" | "entsoe" | "pypsa" | "derived";
            /**
             * T Utc
             * Format: date-time
             */
            t_utc: string;
            /**
             * Unit
             * @enum {string}
             */
            unit: "MW" | "MWh" | "EUR/MWh" | "ratio";
            /** Value */
            value: number | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
};
export type $defs = Record<string, never>;
export interface operations {
    samples_api_samples_get: {
        parameters: {
            query: {
                entity_id: string;
                quantity: "p_gen" | "demand" | "flow" | "soc" | "price" | "strain" | "residual";
                start?: string | null;
                end?: string | null;
                source?: ("energinet" | "entsoe" | "pypsa" | "derived") | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Sample"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
}
