// GENERATED by scripts/gen-api.mjs from the backend OpenAPI document. DO NOT EDIT.
// Regenerate with `npm run gen:api` (frontend/).

export type paths = {
    "/api/samples": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Samples
         * @description Canonical `Sample` rows for one (entity, quantity) in [start, end). Default: last 24h.
         */
        get: operations["samples_api_samples_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/topology": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Topology
         * @description The static network: canonical nodes/edges at the finest level plus the precomputed
         *     cluster views for coarser levels (service A artifact, validated at startup).
         */
        get: operations["get_topology_api_topology_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
};
export type webhooks = Record<string, never>;
export type components = {
    schemas: {
        /** BundledEdge */
        BundledEdge: {
            /** From */
            from: string;
            /** Id */
            id: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "ac_line" | "hvdc_link" | "interconnector";
            /** Length Km */
            length_km: number | null;
            /** Members */
            members: string[];
            /** Rating Mw */
            rating_mw: number | null;
            /** To */
            to: string;
        };
        /** ClusterNode */
        ClusterNode: {
            /** Capacity Mw */
            capacity_mw: {
                [key: string]: number;
            };
            /** Counts */
            counts: {
                [key: string]: number;
            };
            /** Id */
            id: string;
            /** Lat */
            lat: number;
            /** Level */
            level: number;
            /** Lon */
            lon: number;
            /** Members */
            members: string[];
            /** Name */
            name: string;
            /** Zone */
            zone: string;
        };
        /** DbHealth */
        DbHealth: {
            /** Migrations */
            migrations: components["schemas"]["MigrationInfo"][];
            /** Path */
            path: string;
        };
        /** Edge */
        Edge: {
            /** From */
            from: string;
            /** Id */
            id: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "ac_line" | "hvdc_link" | "interconnector";
            /** Length Km */
            length_km?: number | null;
            /**
             * Rating Mw
             * @description thermal limit / NTC; null = unrated virtual connection (bus->load)
             */
            rating_mw: number | null;
            /** To */
            to: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** Health */
        Health: {
            db: components["schemas"]["DbHealth"];
            /** Status */
            status: string;
            /**
             * Time Utc
             * Format: date-time
             */
            time_utc: string;
            /** Version */
            version: string;
        };
        /** LevelInfo */
        LevelInfo: {
            /** Description */
            description: string;
            /** Level */
            level: number;
            /** Name */
            name: string;
        };
        /** LevelView */
        LevelView: {
            /** Edges */
            edges: components["schemas"]["BundledEdge"][];
            /** Nodes */
            nodes: components["schemas"]["ClusterNode"][];
        };
        /** MigrationInfo */
        MigrationInfo: {
            /**
             * Applied At
             * Format: date-time
             */
            applied_at: string;
            /** Name */
            name: string;
            /** Version */
            version: number;
        };
        /** Node */
        Node: {
            /**
             * Capacity Mw
             * @description nameplate power rating (MW); storage: P_max
             */
            capacity_mw?: number | null;
            /**
             * Cluster
             * @description level -> cluster_id; membership in Π_0..Π_L
             */
            cluster?: {
                [key: string]: string;
            };
            /**
             * Co2 Intensity
             * @description tCO2/MWh
             */
            co2_intensity?: number | null;
            /**
             * Energy Mwh
             * @description storage E_max (MWh)
             */
            energy_mwh?: number | null;
            /** Fuel */
            fuel?: string | null;
            /**
             * Id
             * @description stable canonical id
             */
            id: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "source" | "grid" | "consumption" | "storage";
            /** Lat */
            lat: number;
            /** Lon */
            lon: number;
            /** Name */
            name: string;
            /**
             * Voltage Kv
             * @description grid bus nominal voltage
             */
            voltage_kv?: number | null;
            /**
             * Zone
             * @description bidding zone, e.g. 'DK1'
             */
            zone: string;
        };
        /**
         * Sample
         * @description One observation on the canonical time grid.
         *
         *     Join key is (entity_id, quantity, t_utc); `source` is kept in the store's
         *     uniqueness key so two providers may report the same quantity side by side.
         *     A `quality == 'missing'` row carries `value=None` (a dense grid may need an
         *     explicit gap); every other quality requires a finite value.
         */
        Sample: {
            /** Entity Id */
            entity_id: string;
            /**
             * Entity Kind
             * @enum {string}
             */
            entity_kind: "node" | "edge";
            /**
             * Quality
             * @enum {string}
             */
            quality: "measured" | "interpolated" | "estimated" | "missing";
            /**
             * Quantity
             * @enum {string}
             */
            quantity: "p_gen" | "demand" | "flow" | "soc" | "price" | "strain" | "residual";
            /**
             * Resolution
             * @enum {string}
             */
            resolution: "PT5M" | "PT15M" | "PT60M";
            /**
             * Source
             * @enum {string}
             */
            source: "energinet" | "entsoe" | "pypsa" | "derived";
            /**
             * T Utc
             * Format: date-time
             */
            t_utc: string;
            /**
             * Unit
             * @enum {string}
             */
            unit: "MW" | "MWh" | "EUR/MWh" | "ratio";
            /** Value */
            value: number | null;
        };
        /** Topology */
        Topology: {
            /** Edge Members */
            edge_members: {
                [key: string]: string[];
            };
            /** Edges */
            edges: components["schemas"]["Edge"][];
            meta: components["schemas"]["TopologyMeta"];
            /** Nodes */
            nodes: components["schemas"]["Node"][];
            /** Views */
            views: {
                [key: string]: components["schemas"]["LevelView"];
            };
            /** Zones */
            zones: components["schemas"]["ZoneInfo"][];
        };
        /** TopologyMeta */
        TopologyMeta: {
            /** Builder */
            builder: string;
            /** Built At Utc */
            built_at_utc: string;
            /** Finest Level */
            finest_level: number;
            /** Levels */
            levels: components["schemas"]["LevelInfo"][];
            /** Params */
            params: {
                [key: string]: unknown;
            };
            /** Sources */
            sources: {
                [key: string]: string;
            }[];
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** ZoneInfo */
        ZoneInfo: {
            /** Country */
            country: string;
            /** Detail */
            detail: boolean;
            /** Id */
            id: string;
            /** Lat */
            lat: number;
            /** Lon */
            lon: number;
            /** Name */
            name: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
};
export type $defs = Record<string, never>;
export interface operations {
    samples_api_samples_get: {
        parameters: {
            query: {
                entity_id: string;
                quantity: "p_gen" | "demand" | "flow" | "soc" | "price" | "strain" | "residual";
                start?: string | null;
                end?: string | null;
                source?: ("energinet" | "entsoe" | "pypsa" | "derived") | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Sample"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_topology_api_topology_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Topology"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
}
